/* TRG Alert Center V73 — single-source NWS alerts, deduplicated, richer location/detail cards. */
(()=>{
  const box=document.getElementById('alertsBox'); if(!box)return;
  const EVENTS=new Set(['Tornado Warning','Tornado Emergency','Severe Thunderstorm Warning','Extreme Wind Warning','Flash Flood Warning','Flash Flood Emergency','Tornado Watch','Severe Thunderstorm Watch','Special Weather Statement','Severe Weather Statement']);
  const state={items:[],filter:'all',page:1,perPage:20,lastGood:[]};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const type=e=>{const x=String(e||'').toLowerCase();if(x.includes('tornado'))return'tornado';if(x.includes('severe thunderstorm')||x.includes('extreme wind'))return'severe';if(x.includes('flash flood'))return'flash';if(x.includes('watch'))return'watch';return'statement'};
  const rank={tornado:1000,severe:900,flash:800,watch:700,statement:600};
  const ongoing=p=>{const s=String(p?.status||'Actual').toLowerCase(),m=String(p?.messageType||'Alert').toLowerCase(),eff=Date.parse(p?.effective||p?.onset||p?.sent||''),exp=Date.parse(p?.expires||p?.ends||'');return(s==='actual'||s==='active')&&m!=='cancel'&&(!Number.isFinite(eff)||eff<=Date.now())&&(!Number.isFinite(exp)||exp>Date.now())};
  const target=f=>EVENTS.has(String(f?.properties?.event||'').trim())&&ongoing(f.properties);
  const matches=(item,filter)=>filter==='all'||(filter==='warning'?['tornado','severe','flash'].includes(type(item.properties?.event)):type(item.properties?.event)===filter);
  const dedupe=a=>{const seen=new Map();for(const f of a){const p=f.properties||{},id=String(f.id||p.identifier||p.id||'').trim();const key=id||[p.event,p.senderName,p.effective||p.onset,p.expires||p.ends,p.areaDesc,p.headline].map(v=>String(v||'').trim()).join('|');if(!seen.has(key))seen.set(key,f)}return[...seen.values()]};
  const states={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming',DC:'District of Columbia'};
  const getStates=p=>{const found=new Set(),area=String(p?.areaDesc||'');for(const code of Object.keys(states)){if(new RegExp(`(?:^|[^A-Z])${code}(?:$|[^A-Z])`,'i').test(area)||new RegExp(`(?:^|[; ,])${states[code]}(?:$|[; ,])`,'i').test(area))found.add(code)}for(const raw of (Array.isArray(p?.geocode?.UGC)?p.geocode.UGC:p?.geocode?.UGC?[p.geocode.UGC]:[])){const m=String(raw).match(/^([A-Z]{2})[CZ]/i);if(m&&states[m[1].toUpperCase()])found.add(m[1].toUpperCase())}const sender=String(p?.senderName||'');const sm=sender.match(/\b([A-Z]{2})\b\s*$/);if(sm&&states[sm[1]])found.add(sm[1]);return[...found].map(x=>states[x]).join(', ')};
  const areas=p=>String(p?.areaDesc||'Active NWS area').split(';').map(x=>x.trim()).filter(Boolean);
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const trim=(s,n)=>{const d=clean(s);return d?(d.length>n?d.slice(0,n-1)+'…':d):''};
  function render(){
    const list=[...state.items].filter(x=>target(x)&&matches(x,state.filter)).sort((a,b)=>rank[type(b.properties?.event)]-rank[type(a.properties?.event)]||Date.parse(a.properties?.expires||'')-Date.parse(b.properties?.expires||''));
    const pages=Math.max(1,Math.ceil(list.length/state.perPage));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.perPage,visible=list.slice(start,start+state.perPage);
    box.innerHTML=visible.length?visible.map((x,i)=>{const p=x.properties||{},k=type(p.event),color=k==='tornado'?'#ef4444':k==='severe'?'#f97316':k==='flash'?'#22c55e':k==='watch'?'#ffd52e':'#a78bfa',considerable=k==='severe'&&/considerable/i.test(`${p.headline||''} ${p.description||''} ${p.instruction||''}`),id=String(x.id||p.identifier||''),issued=p.sent||p.effective||p.onset,expires=p.expires||p.ends,sts=getStates(p)||'State not provided',ar=areas(p),wfo=p.senderName||p.wfo||'National Weather Service';return`<a class="alert ${k} ${considerable?'alert-considerable':''}" data-alert-id="${esc(id)}" href="maps.html?alert=${encodeURIComponent(id)}" style="border-color:${color}!important;box-shadow:0 0 0 1px ${color}22 inset"><div class="alert-rank">${start+i+1}</div><div class="alert-icon" style="background:${color}">${k==='watch'?'W':k==='statement'?'S':'!'}</div><div class="alert-body"><div class="alert-title-row"><strong>${esc(p.event||'Weather Alert')}</strong><span class="alert-priority">${esc(p.severity||'Unknown')} • ${esc(p.urgency||'Unknown')}</span></div><span class="alert-headline">${esc(p.headline||p.event||'')}</span><div class="alert-location"><b>${esc(sts)}</b>${ar.length?`<span>${esc(ar.slice(0,10).join(' • '))}</span>`:''}</div><small>Issued ${issued?esc(new Date(issued).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})):'Unknown'} · Expires ${expires?esc(new Date(expires).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})):'Unknown'} · ${esc(wfo)}</small>${trim(p.description,500)?`<p class="alert-description"><b>Details:</b> ${esc(trim(p.description,500))}</p>`:''}${trim(p.instruction,320)?`<p class="alert-instruction"><b>Instructions:</b> ${esc(trim(p.instruction,320))}</p>`:''}</div></a>`}).join(''):`<div class="empty"><strong>No ${state.filter==='all'?'target':state.filter} alerts found.</strong><br><small>Generic Flood Warnings are excluded.</small></div>`;
    let pager=document.getElementById('trgAlertPager');if(!pager){pager=document.createElement('div');pager.id='trgAlertPager';pager.className='trg-alert-pager';box.after(pager)}pager.innerHTML=pages>1?`<button type="button" id="trgPrev" ${state.page===1?'disabled':''}>← PREVIOUS</button><span>PAGE ${state.page} OF ${pages} • ${list.length} ALERTS</span><button type="button" id="trgNext" ${state.page===pages?'disabled':''}>NEXT →</button>`:`<span>${list.length} ACTIVE TARGET ALERT${list.length===1?'':'S'} • FLOOD WARNINGS EXCLUDED</span>`;document.getElementById('trgPrev')?.addEventListener('click',()=>{state.page--;render()});document.getElementById('trgNext')?.addEventListener('click',()=>{state.page++;render()});
    const severe=state.items.filter(x=>target(x)&&type(x.properties?.event)==='severe').length,tornado=state.items.filter(x=>target(x)&&type(x.properties?.event)==='tornado').length,flash=state.items.filter(x=>target(x)&&type(x.properties?.event)==='flash').length,total=state.items.filter(target).length;document.getElementById('alertCount')?.replaceChildren(document.createTextNode(String(severe)));document.getElementById('localAlertCount')?.replaceChildren(document.createTextNode(String(total)));const u=document.getElementById('alertsUpdated');if(u)u.textContent=`Updated ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} • live NWS/NOAA feed`;const tag=document.getElementById('alertTag');if(tag){tag.textContent=`${total} ACTIVE`;tag.className='tag red'}const note=document.querySelector('.alert-summary-note');if(note)note.textContent=`${severe} severe thunderstorm warnings • ${tornado} tornado warnings • ${flash} flash flood warnings • generic Flood Warnings excluded.`;
  }
  async function getNws(){const r=await fetch(`https://api.weather.gov/alerts/active?limit=5000&_trg73=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/geo+json,application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const d=await r.json();if(!Array.isArray(d.features))throw new Error('Invalid NWS response');return dedupe(d.features.filter(target))}
  async function refresh(){try{const items=await getNws();state.items=items;state.lastGood=items;state.page=1;render()}catch(e){console.warn('TRG alerts refresh failed',e);if(state.lastGood.length){state.items=state.lastGood.filter(x=>ongoing(x.properties));render()}else{try{const r=await fetch(`https://api.weather.gov/alerts/active?status=actual&message_type=alert&limit=5000&_trg73fallback=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/geo+json'}});const d=await r.json();state.items=dedupe((d.features||[]).filter(target));state.lastGood=state.items;render()}catch(_){render()}}const u=document.getElementById('alertsUpdated');if(u)u.textContent='NWS refresh delayed • showing last confirmed alerts'}}
  window.renderAlertCards=render;window.renderAlerts=data=>{state.items=dedupe((data?.features||[]).filter(target));state.lastGood=state.items;state.page=1;render()};document.querySelectorAll('.alert-filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.alert-filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.alertFilter||'all';state.page=1;render()}));document.getElementById('alertsRefresh')?.addEventListener('click',refresh);refresh();setInterval(refresh,60000);
})();
