/* TRG Weather Alerts V79 — live NWS with repo-cached fallback. */
(()=>{
const box=document.getElementById('alertsBox');if(!box)return;let data=[],filter='all',busy=false;
const states={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming',DC:'District of Columbia'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function kind(e){const x=String(e||'').toLowerCase();if(x.includes('tornado'))return'tornado';if(x.includes('severe thunderstorm')||x.includes('extreme wind'))return'severe';if(x.includes('flash flood'))return'flash';if(x.includes('watch'))return'watch';if(x.includes('statement'))return'statement';return'advisory'}
function state(p){const out=[];const add=x=>{if(x&&!out.includes(x))out.push(x)};for(const u of p?.geocode?.UGC||[]){const m=String(u).toUpperCase().match(/^([A-Z]{2})[CZ]\d{3}$/);if(m&&states[m[1]])add(states[m[1]])}const a=String(p?.areaDesc||'');for(const [c,n] of Object.entries(states)){if(new RegExp(`(^|[ ,;])${c}([ ,;]|$)`,'i').test(a))add(n);else if(new RegExp(`(^|[^A-Za-z])${n}([^A-Za-z]|$)`,'i').test(a))add(n)}return out.join(', ')||'State not provided'}
function active(f){const p=f.properties||{},ex=Date.parse(p.expires||p.ends||'');return String(p.status||'Actual').toLowerCase()!=='cancel'&&String(p.messageType||'Alert').toLowerCase()!=='cancel'&&(!Number.isFinite(ex)||ex>Date.now())}
function clean(fs){const m=new Map();for(const f of fs||[]){const p=f.properties||{},e=String(p.event||'');if(!active(f)||/^flood warning$/i.test(e))continue;const k=String(f.id||p.identifier||`${e}|${p.effective}|${p.expires}|${p.areaDesc}`);if(!m.has(k))m.set(k,f)}const rank={tornado:9,severe:8,flash:7,watch:6,statement:5,advisory:4};return[...m.values()].sort((a,b)=>(rank[kind(b.properties?.event)]||0)-(rank[kind(a.properties?.event)]||0))}
function filtered(){return filter==='all'?data:data.filter(f=>{const k=kind(f.properties?.event);return filter==='warning'?['tornado','severe','flash'].includes(k):k===filter})}
function render(){const fs=filtered();box.innerHTML=fs.length?fs.map((f,i)=>{const p=f.properties||{},k=kind(p.event),considerable=k==='severe'&&/considerable/i.test(`${p.event} ${p.headline||''} ${p.description||''}`),c=considerable?'#f97316':k==='tornado'?'#ef4444':k==='severe'?'#f97316':k==='flash'?'#22c55e':k==='watch'?'#ffd52e':k==='statement'?'#a78bfa':'#60a5fa',id=f.id||p.identifier||'',areas=String(p.areaDesc||'').split(';').map(x=>x.trim()).filter(Boolean).join(' • ');return`<article class="alert ${k}${considerable?' alert-considerable':''}" data-alert-id="${esc(id)}" style="border-color:${c}!important;cursor:pointer"><div class="alert-rank">${i+1}</div><div class="alert-icon" style="background:${c}">${k==='watch'?'W':k==='statement'?'S':k==='advisory'?'A':'!'}</div><div class="alert-body"><div class="alert-title-row"><strong>${esc(considerable?'CONSIDERABLE '+p.event:(p.event||'Weather Alert'))}</strong><span class="alert-priority">${esc(p.severity||'')} ${p.urgency?'• '+esc(p.urgency):''}</span></div><span class="alert-headline">${esc(p.headline||p.event||'')}</span><div class="alert-location"><b>${esc(state(p))}</b><span>${esc(areas||'Affected area not provided')}</span></div><small>Issued ${p.sent?new Date(p.sent).toLocaleString():p.effective?new Date(p.effective).toLocaleString():'Unknown'} · Expires ${p.expires?new Date(p.expires).toLocaleString():'Unknown'} · ${esc(p.senderName||'National Weather Service')}</small>${p.description?`<p class="alert-description"><b>Details:</b> ${esc(String(p.description).replace(/\s+/g,' ').trim())}</p>`:''}${p.instruction?`<p class="alert-instruction"><b>Instructions:</b> ${esc(String(p.instruction).replace(/\s+/g,' ').trim())}</p>`:''}<small class="alert-radar-link">CLICK TO VIEW THIS ALERT ON RADAR →</small></div></article>`}).join(''):'<div class="empty">No matching active alerts.<br><small>Generic Flood Warnings are excluded.</small></div>';document.getElementById('alertCount')?.replaceChildren(document.createTextNode(String(data.filter(f=>kind(f.properties?.event)==='severe').length)));document.getElementById('localAlertCount')?.replaceChildren(document.createTextNode(String(data.length)));document.getElementById('alertsUpdated')?.replaceChildren(document.createTextNode(`Updated ${new Date().toLocaleTimeString()} • live NWS feed`));document.getElementById('alertTag')?.replaceChildren(document.createTextNode(`${data.length} ACTIVE`))}
async function getLive(){const r=await fetch(`https://api.weather.gov/alerts/active?limit=500&_trg79=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/geo+json,application/json'}});if(!r.ok)throw Error(r.status);const d=await r.json();if(!Array.isArray(d.features))throw Error('Invalid NWS response');return d.features}
async function getFallback(){const r=await fetch(`./alerts.json?_trg79=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw Error(r.status);const d=await r.json();if(!Array.isArray(d.features))throw Error('Invalid cached alert data');return d.features}
async function refresh(){if(busy)return;busy=true;try{let fs;let source='live NWS';try{fs=await getLive()}catch(e){console.warn('Live NWS alerts unavailable, using repo cache',e);fs=await getFallback();source='NWS cache fallback'}data=clean(fs);render();document.getElementById('alertsUpdated')?.replaceChildren(document.createTextNode(`Updated ${new Date().toLocaleTimeString()} • ${source}`))}catch(e){console.warn('Alerts V79 failed',e);box.innerHTML='<div class="empty"><strong>Weather alert feed unavailable.</strong><br><small>The site could not reach the live NWS feed or its latest cached copy. Try REFRESH.</small></div>'}finally{busy=false}}
document.querySelectorAll('.alert-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.alert-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.alertFilter||'all';render()});document.getElementById('alertsRefresh')?.addEventListener('click',refresh);box.addEventListener('click',e=>{const card=e.target.closest('[data-alert-id]');if(card?.dataset.alertId)location.href='maps.html?alert='+encodeURIComponent(card.dataset.alertId)});refresh();setInterval(refresh,60000);
})();
