/* TRG Weather Alerts V77 — simple, resilient NWS active-alert renderer. */
(()=>{
const box=document.getElementById('alertsBox');if(!box)return;
const states={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming',DC:'District of Columbia'};
let alerts=[],filter='all',busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kind=e=>{const x=String(e||'').toLowerCase();if(x.includes('tornado'))return'tornado';if(x.includes('severe thunderstorm')||x.includes('extreme wind'))return'severe';if(x.includes('flash flood'))return'flash';if(x.includes('watch'))return'watch';if(x.includes('statement'))return'statement';if(x.includes('warning'))return'warning';return'advisory'};
const active=p=>{const ex=Date.parse(p?.expires||p?.ends||'');return String(p?.status||'Actual').toLowerCase()!=='cancel'&&String(p?.messageType||'Alert').toLowerCase()!=='cancel'&&(!Number.isFinite(ex)||ex>Date.now())};
function getStates(p){const out=[];const add=s=>{if(s&&!out.includes(s))out.push(s)};for(const u of (Array.isArray(p?.geocode?.UGC)?p.geocode.UGC:[])){const m=String(u).toUpperCase().match(/^([A-Z]{2})[CZ]\d{3}$/);if(m&&states[m[1]])add(states[m[1]])}const a=String(p?.areaDesc||'');for(const [code,name] of Object.entries(states)){if(new RegExp(`(?:^|[ ,;])${code}(?:$|[ ,;])`,'i').test(a))add(name);if(new RegExp(`\\b${name.replace(/ /g,'\\s+')}\\b`,'i').test(a))add(name)}return out.join(', ')}
function areas(p){return String(p?.areaDesc||'').split(';').map(x=>x.trim()).filter(Boolean).join(' • ')}
function dedupe(fs){const m=new Map();for(const f of fs||[]){const p=f.properties||{};if(!active(p)||/^flood warning$/i.test(p.event||''))continue;const key=String(f.id||p.identifier||`${p.event}|${p.effective}|${p.expires}|${p.areaDesc}`);if(!m.has(key))m.set(key,f)}return[...m.values()]}
function filtered(){let fs=alerts.slice();if(filter!=='all')fs=fs.filter(f=>{const k=kind(f.properties?.event);if(filter==='warning')return['tornado','severe','flash','warning'].includes(k);return k===filter});const rank={tornado:8,severe:7,flash:6,watch:5,warning:4,statement:3,advisory:2};return fs.sort((a,b)=>(rank[kind(b.properties?.event)]||0)-(rank[kind(a.properties?.event)]||0))}
function render(){const fs=filtered();box.innerHTML=fs.length?fs.map((f,i)=>{const p=f.properties||{},k=kind(p.event),state=getStates(p)||'State not provided',area=areas(p)||'Affected area not provided',id=f.id||p.identifier||'',considerable=k==='severe'&&/considerable/i.test(`${p.event} ${p.headline} ${p.description}`),c=considerable?'#f97316':k==='tornado'?'#ef4444':k==='severe'?'#f97316':k==='flash'?'#22c55e':k==='watch'?'#ffd52e':k==='statement'?'#a78bfa':'#60a5fa';return`<article class="alert ${k}${considerable?' alert-considerable':''}" data-alert-id="${esc(id)}" style="border-color:${c}!important;cursor:pointer"><div class="alert-rank">${i+1}</div><div class="alert-icon" style="background:${c}">${k==='watch'?'W':k==='statement'?'S':k==='advisory'?'A':'!'}</div><div class="alert-body"><div class="alert-title-row"><strong>${esc(considerable?'CONSIDERABLE '+p.event:(p.event||'Weather Alert'))}</strong><span class="alert-priority">${esc(p.severity||'Unknown')} • ${esc(p.urgency||'Unknown')}</span></div><span class="alert-headline">${esc(p.headline||p.event||'')}</span><div class="alert-location"><b>${esc(state)}</b><span>${esc(area)}</span></div><small>Issued ${p.sent?new Date(p.sent).toLocaleString():p.effective?new Date(p.effective).toLocaleString():'Unknown'} · Expires ${p.expires?new Date(p.expires).toLocaleString():'Unknown'} · ${esc(p.senderName||'National Weather Service')}</small>${p.description?`<p class="alert-description"><b>Details:</b> ${esc(String(p.description).replace(/\s+/g,' ').trim())}</p>`:''}${p.instruction?`<p class="alert-instruction"><b>Instructions:</b> ${esc(String(p.instruction).replace(/\s+/g,' ').trim())}</p>`:''}<small class="alert-radar-link">CLICK TO VIEW THIS ALERT ON RADAR →</small></div></article>`}).join(''):'<div class="empty">No matching active alerts.<br><small>Generic Flood Warnings are excluded from this page.</small></div>';
const severe=alerts.filter(f=>kind(f.properties?.event)==='severe').length;document.getElementById('alertCount')?.replaceChildren(document.createTextNode(String(severe)));document.getElementById('localAlertCount')?.replaceChildren(document.createTextNode(String(alerts.length)));const u=document.getElementById('alertsUpdated');if(u)u.textContent=`Updated ${new Date().toLocaleTimeString()} • live NWS/NOAA feed`;const tag=document.getElementById('alertTag');if(tag)tag.textContent=`${alerts.length} ACTIVE`}
async function getJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/geo+json'}});if(!r.ok)throw Error(`${r.status}`);return r.json()}
async function refresh(){if(busy)return;busy=true;try{let d;try{d=await getJson(`https://api.weather.gov/alerts/active?_trg77=${Date.now()}`)}catch(e){d=await getJson(`https://api.weather.gov/alerts/active?limit=500&_trg77=${Date.now()}`)}alerts=dedupe(d.features||[]);render()}catch(e){console.warn('Alerts V77 failed',e);box.innerHTML='<div class="empty">NWS active alert feed temporarily unavailable.<br><small>Click REFRESH to try again.</small></div>'}finally{busy=false}}
document.querySelectorAll('.alert-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.alert-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.alertFilter||'all';render()}));document.getElementById('alertsRefresh')?.addEventListener('click',refresh);box.addEventListener('click',e=>{const card=e.target.closest('.alert[data-alert-id]');if(card?.dataset.alertId)location.href='maps.html?alert='+encodeURIComponent(card.dataset.alertId)});refresh();setInterval(refresh,60000);
})();
