/* Alert-center recovery: query each NWS event type directly so no event class can be truncated by one feed page. */
(() => {
  const box=document.getElementById("alertsBox"); if(!box) return;
  const state={all:[],filter:"all",page:1,perPage:20};
  const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const kind=e=>{e=String(e||"").toLowerCase();if(e.includes("tornado emergency")||e.includes("tornado warning"))return"tornado";if(e.includes("severe thunderstorm warning")||e.includes("extreme wind warning"))return"severe";if(e.includes("flash flood warning")||e.includes("flash flood emergency"))return"flash";if(e.includes("tornado watch")||e.includes("severe thunderstorm watch"))return"watch";if(e.includes("advisory"))return"advisory";if(e.includes("statement"))return"statement";return"other";};
  const pri={tornado:1000,severe:900,flash:800,watch:700,advisory:600,statement:500,other:-1};
  const target=new Set(["Tornado Warning","Tornado Emergency","Severe Thunderstorm Warning","Extreme Wind Warning","Flash Flood Warning","Flash Flood Emergency","Tornado Watch","Severe Thunderstorm Watch"]);
  const eventUrls=[...target].map(e=>`https://api.weather.gov/alerts/active?event=${encodeURIComponent(e)}&limit=5000`);
  const active=p=>{const s=String(p?.status||"Actual").toLowerCase();const m=String(p?.messageType||"Alert").toLowerCase();const x=Date.parse(p?.expires||p?.ends||"");return (s==="actual"||s==="active")&&m!=="cancel"&&(!Number.isFinite(x)||x>Date.now());};
  async function get(url){const r=await fetch(url,{cache:"no-store",headers:{Accept:"application/geo+json"}});if(!r.ok)throw new Error(`${r.status}`);return r.json();}
  function render(){let a=state.all.filter(x=>{const k=kind(x.properties?.event);return state.filter==="all"?k!=="other":state.filter==="warning"?["tornado","severe","flash"].includes(k):state.filter===k});a.sort((x,y)=>pri[kind(y.properties?.event)]-pri[kind(x.properties?.event)]||Date.parse(y.properties?.sent||0)-Date.parse(x.properties?.sent||0));const pages=Math.max(1,Math.ceil(a.length/state.perPage));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.perPage;box.innerHTML=a.slice(start,start+state.perPage).map((x,i)=>{const p=x.properties||{},k=kind(p.event),considerable=k==="severe"&&/considerable/i.test(`${p.headline||""} ${p.description||""}`);const colors={tornado:"#ef4444",severe:considerable?"#f97316":"#f97316",flash:"#22c55e",watch:"#ffd52e",advisory:"#60a5fa",statement:"#a78bfa"};const href=/^https:\/\//.test(p.web||"")?p.web:"https://www.weather.gov/alerts";return `<a class="alert" style="border-color:${colors[k]||"#64748b"};box-shadow:0 0 0 1px ${colors[k]||"#64748b"}22 inset" href="${esc(href)}" target="_blank" rel="noopener"><div class="alert-rank">${start+i+1}</div><div class="alert-icon" style="background:${colors[k]||"#64748b"}">${k==="watch"?"W":k==="advisory"?"A":k==="statement"?"S":"!"}</div><div class="alert-body"><div class="alert-title-row"><strong>${esc(p.event||"Weather Alert")}</strong><span class="alert-priority">${esc(p.severity||"Unknown")} • ${esc(p.urgency||"Unknown")}</span></div><span>${esc(p.headline||p.event||"")}</span><small>${esc(String(p.areaDesc||"Active NWS area").split(";").slice(0,3).join(" • "))}</small></div></a>`}).join("")||`<div class="empty"><strong>No alerts in this category.</strong></div>`;let pg=document.getElementById("trgAlertPager");if(!pg){pg=document.createElement("div");pg.id="trgAlertPager";pg.className="trg-alert-pager";box.after(pg)}pg.innerHTML=pages>1?`<button ${state.page===1?"disabled":""} id="alertPrev">← PREVIOUS</button><span>PAGE ${state.page} OF ${pages} • ${a.length} ALERTS</span><button ${state.page===pages?"disabled":""} id="alertNext">NEXT →</button>`:`<span>${a.length} ACTIVE ALERT${a.length===1?"":"S"} • ALL ALERTS SHOWN`;$('alertPrev')?.addEventListener("click",()=>{state.page--;render()});$('alertNext')?.addEventListener("click",()=>{state.page++;render()});const severe=state.all.filter(x=>kind(x.properties?.event)==="severe").length,tornado=state.all.filter(x=>kind(x.properties?.event)==="tornado").length;if(document.getElementById("alertCount"))document.getElementById("alertCount").textContent=severe;if(document.getElementById("localAlertCount"))document.getElementById("localAlertCount").textContent=state.all.length;if(document.getElementById("alertsUpdated"))document.getElementById("alertsUpdated").textContent=`Updated ${new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})} • direct NWS event feeds`;
  }
  async function refresh(){try{const sets=await Promise.all(eventUrls.map(get));const map=new Map();sets.flatMap(x=>Array.isArray(x?.features)?x.features:[]).filter(x=>active(x.properties)).forEach(x=>map.set(String(x.id),x));state.all=[...map.values()];state.page=1;render();}catch(e){console.warn("TRG alert event feeds failed",e);if(document.getElementById("alertsUpdated"))document.getElementById("alertsUpdated").textContent="NWS event feeds unavailable • retrying";}}
  const $=s=>document.querySelector(s);
  document.querySelectorAll(".alert-filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".alert-filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.alertFilter||"all";state.page=1;render()}));
  document.getElementById("alertsRefresh")?.addEventListener("click",refresh);refresh();setInterval(refresh,60000);
})();
