/* TRG Radar SPC V80 — independent controls; Severe page untouched. */
(()=>{
const SPC='https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/SPC_wx_outlks/FeatureServer';const layers={categorical:1,tornado:3,wind:7,hail:5,windCig:6,hailCig:4};let M=null,ready=false,overlay={},cig={};
const colors=(n,k)=>{const v=Number(n);if(k==='tornado')return({2:'#48a868',5:'#7b5a3b',10:'#b07d3c',15:'#f3d34a',30:'#f28c28',45:'#e53935',60:'#d94ad8',75:'#8f2bbd',90:'#5b147f'}[v]||'#d8c39a');return({2:'#c1e9c1',5:'#7b5a3b',10:'#b07d3c',15:'#f3d34a',30:'#f28c28',45:'#e53935',60:'#d94ad8',75:'#8f2bbd',90:'#5b147f'}[v]||'#d8c39a')};
function init(){if(ready||!window.__trgRadarMap||!window.L)return;M=window.__trgRadarMap;ready=true;const d=document.createElement('div');d.id='trgSpc80';d.style.cssText='display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-top:10px';d.innerHTML='<span style="font:900 9px Arial;color:#8d94a7;letter-spacing:1px">SPC</span><button data-k="categorical">SPC RISK</button><button data-k="tornado">TORNADO</button><button data-k="wind">WIND</button><button data-k="hail">HAIL</button>';d.querySelectorAll('button').forEach(b=>{b.style.cssText='background:#0d1017;color:#b8bdca;border:1px solid #ffffff18;border-radius:6px;padding:7px 9px;font:900 9px Arial;cursor:pointer';b.onclick=()=>{const on=b.dataset.on!=='1';b.dataset.on=on?'1':'0';b.style.background=on?'#180b0b':'#0d1017';b.style.color=on?'#fff':'#b8bdca';toggle(b.dataset.k,on)}});document.querySelector('.radar-toolbar')?.appendChild(d)}
async function toggle(k,on){if(!M)return;if(!on){if(overlay[k]){M.removeLayer(overlay[k]);overlay[k]=null}if(cig[k]){M.removeLayer(cig[k]);cig[k]=null}return}try{const r=await fetch(`${SPC}/${layers[k]}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg80=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();overlay[k]=L.geoJSON(d,{style:f=>{const p=f.properties||{},n=Number(p.dn??p.DN??p.prob??p.PROB);return{color:'#333',weight:1.3,fillColor:k==='categorical'?({2:'#c1e9c1',3:'#66a366',4:'#ffe066',5:'#ffa366',6:'#e06666',8:'#ee99ee'}[n]||'#d9d9d9'):colors(n,k),fillOpacity:.30}}}).addTo(M);if(k==='wind'||k==='hail')await loadCig(k)}catch(e){console.warn('V80 SPC overlay failed',e)}}
async function loadCig(k){if(cig[k])M.removeLayer(cig[k]);const layer=k==='wind'?layers.windCig:layers.hailCig;try{const r=await fetch(`${SPC}/${layer}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg80=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();const fs=(d.features||[]).filter(f=>{const p=f.properties||{},x=String(p.label||p.LABEL||p.cig||'').toUpperCase();return /^CIG[123]$/.test(x)||['1','2','3'].includes(String(p.dn??p.DN??''))});cig[k]=L.geoJSON({...d,features:fs},{style:f=>{const p=f.properties||{},x=String(p.label||p.LABEL||p.cig||'').toUpperCase()||({1:'CIG1',2:'CIG2',3:'CIG3'}[String(p.dn??p.DN??'')]||'CIG1');const fill=x==='CIG1'?'#ffffff':x==='CIG2'?'#ffd52e':'#f97316';return{color:'#111',weight:2,fillColor:fill,fillOpacity:.20,dashArray:x==='CIG1'?'8 5':x==='CIG2'?'12 5':'4 4'}},onEachFeature:(f,l)=>l.bindTooltip(String(f.properties?.label||f.properties?.LABEL||f.properties?.cig||'CIG'),{sticky:true})}}).addTo(M)}catch(e){console.warn('V80 CIG failed',e)}}
const t=setInterval(()=>{if(window.__trgRadarMap){clearInterval(t);init()}},100);setTimeout(()=>clearInterval(t),30000);if(window.__trgRadarMap)init();
})();
