/* TRG Radar Room V68
   Adds optional single-site NEXRAD, active target warnings, and SPC overlays.
   Uses official NOAA/NWS services. */
(() => {
  const TARGET_EVENTS = new Set(['Tornado Warning','Tornado Emergency','Severe Thunderstorm Warning','Extreme Wind Warning','Flash Flood Warning','Flash Flood Emergency','Tornado Watch','Severe Thunderstorm Watch']);
  const COLORS = { tornado:'#ef4444', severe:'#f97316', flash:'#22c55e', watch:'#ffd52e' };
  const RADARS = [
    ['KINX','Tulsa / Inola, OK',35.095,-95.564],['KTLX','Norman / Oklahoma City, OK',35.333,-97.277],['KVNX','Vance AFB, OK',36.741,-98.128],['KOUN','Norman Testbed, OK',35.238,-97.460],
    ['KICT','Wichita, KS',37.654,-97.443],['KDDC','Dodge City, KS',37.760,-99.968],['KSGF','Springfield, MO',37.235,-93.401],['KPAH','Paducah, KY',37.068,-88.772],
    ['KLSX','St. Louis, MO',38.699,-90.683],['KOHX','Nashville, TN',36.247,-86.563],['KHTX','Huntsville, AL',34.930,-86.084],['KDGX','Jackson, MS',32.280,-89.984],
    ['KSHV','Shreveport, LA',32.450,-93.841],['KHGX','Houston, TX',29.471,-95.079],['KFWS','Fort Worth, TX',32.573,-97.303],['KEWX','Austin/San Antonio, TX',29.704,-98.029],
    ['KAMA','Amarillo, TX',35.233,-101.709],['KLBB','Lubbock, TX',33.654,-101.814],['KABR','Aberdeen, SD',45.456,-98.413],['KMPX','Minneapolis, MN',44.849,-93.565],
    ['KLOT','Chicago, IL',41.604,-88.085],['KILX','Lincoln, IL',40.150,-89.336],['KIND','Indianapolis, IN',39.707,-86.280],['KIWX','Northern Indiana, IN',41.358,-85.700],
    ['KRLX','Charleston, WV',38.312,-81.723],['KPBZ','Pittsburgh, PA',40.531,-80.218],['KLWX','Sterling, VA',38.976,-77.487],['KAKQ','Wakefield, VA',36.984,-77.007],
    ['KRAH','Raleigh, NC',35.665,-78.491],['KMHX','Morehead City, NC',34.776,-76.876],['KJAX','Jacksonville, FL',30.485,-81.701],['KMLB','Melbourne, FL',28.114,-80.654],
    ['KTBW','Tampa, FL',27.705,-82.401],['KAMX','Miami, FL',25.611,-80.413],['KBYX','Key West, FL',24.597,-81.703],['KMSX','Missoula, MT',47.041,-113.986],
    ['KATX','Seattle, WA',48.195,-122.496],['KRTX','Portland, OR',45.715,-122.965],['KMUX','San Francisco, CA',37.155,-121.898],['KHNX','San Joaquin Valley, CA',36.314,-119.632],
    ['KSOX','Santa Ana Mountains, CA',33.818,-117.636],['KEMX','Tucson, AZ',31.893,-110.630],['KBYX','Key West, FL',24.597,-81.703]
  ];
  const SPC_URL='https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/SPC_wx_outlks/FeatureServer';
  const SPC_LAYERS={categorical:1,tornado:3,wind:7,hail:5};
  let warningLayer, spcLayers={}, sitePanel;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const eventKind=e=>{e=String(e||'').toLowerCase();if(e.includes('tornado'))return'tornado';if(e.includes('severe thunderstorm')||e.includes('extreme wind'))return'severe';if(e.includes('flash flood'))return'flash';if(e.includes('watch'))return'watch';return'warning'};
  const active=p=>{const x=Date.parse(p?.expires||p?.ends||'');return String(p?.messageType||'Alert').toLowerCase()!=='cancel'&&(!Number.isFinite(x)||x>Date.now());};
  function controls(){const host=document.querySelector('.radar-toolbar');if(!host||document.getElementById('trgRadarLayers'))return;const box=document.createElement('div');box.id='trgRadarLayers';box.className='trg-radar-controls';box.innerHTML=`<span class="trg-layer-title">LAYERS</span><button data-layer="warnings" class="trg-layer-btn active">⚠ WARNINGS</button><button data-layer="categorical" class="trg-layer-btn">SPC RISK</button><button data-layer="tornado" class="trg-layer-btn">TORNADO</button><button data-layer="wind" class="trg-layer-btn">WIND</button><button data-layer="hail" class="trg-layer-btn">HAIL</button><button data-layer="site" class="trg-layer-btn">HIGH-RES SITE</button>`;host.appendChild(box);box.addEventListener('click',e=>{const b=e.target.closest('[data-layer]');if(!b)return;const k=b.dataset.layer;b.classList.toggle('active');if(k==='warnings')toggleWarnings(b.classList.contains('active'));else if(k==='site')toggleSite(b.classList.contains('active'));else toggleSPC(k,b.classList.contains('active'));});
  }
  async function toggleWarnings(on){if(!window.state?.map)return;if(!on){if(warningLayer)state.map.removeLayer(warningLayer);return;}await loadWarnings();}
  async function loadWarnings(focusId=null){if(!window.state?.map||!window.L)return;try{const r=await fetch(`https://api.weather.gov/alerts/active?limit=5000&_trgRadar=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/geo+json,application/json'}});const d=await r.json();const fs=(d.features||[]).filter(f=>TARGET_EVENTS.has(String(f.properties?.event||''))&&active(f.properties));if(warningLayer)state.map.removeLayer(warningLayer);warningLayer=L.layerGroup().addTo(state.map);let focus=null;fs.forEach(f=>{if(!f.geometry)return;const p=f.properties||{},k=eventKind(p.event),c=COLORS[k]||'#ef4444';const layer=L.geoJSON(f,{style:{color:c,weight:2.5,fillColor:c,fillOpacity:.18},onEachFeature:(_,lyr)=>{lyr.bindPopup(`<strong>${esc(p.event||'Weather Warning')}</strong><br><b>${esc((p.areaDesc||'').split(';').slice(0,3).join(' • '))}</b><br>${esc(p.headline||'')}<br><small>Expires ${p.expires?new Date(p.expires).toLocaleString(): 'unknown'}</small><br><a href="${esc(p.web||'https://www.weather.gov/alerts')}" target="_blank" rel="noopener">Official NWS alert →</a>`);if(focusId&&String(f.id)===focusId)focus=lyr;}});layer.addTo(warningLayer);});if(focus){setTimeout(()=>{const b=focus.getBounds?.();if(b?.isValid()){state.map.fitBounds(b.pad(.35),{animate:false});focus.openPopup();}},100);} }catch(e){console.warn('TRG warning overlay failed',e)}}
  async function toggleSPC(key,on){if(!window.state?.map||!window.L)return;if(!on){if(spcLayers[key])state.map.removeLayer(spcLayers[key]);return;}try{const url=`${SPC_URL}/${SPC_LAYERS[key]}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg=${Date.now()}`;const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(spcLayers[key])state.map.removeLayer(spcLayers[key]);spcLayers[key]=L.geoJSON(d,{style:f=>{const p=f.properties||{},dn=Number(p.dn),fills=key==='categorical'?({2:'#c1e9c1',3:'#66a366',4:'#ffe066',5:'#ffa366',6:'#e06666',8:'#ee99ee'}):({2:'#c1e9c1',5:'#ffa366',10:'#ffe066',15:'#e06666',30:'#ee99ee',45:'#d85bd8',60:'#b22bce',75:'#8b008b',90:'#6b006b'});const fill=typeof p.fill==='string'&&p.fill? p.fill:(fills[dn]||'#d9d9d9');return{color:'#333',weight:1.4,fillColor:fill,fillOpacity:.32};},onEachFeature:(f,l)=>{const p=f.properties||{};l.bindTooltip(`${key.toUpperCase()} ${esc(p.label||p.label2||p.dn||'OUTLOOK')}`,{sticky:true});}}).addTo(state.map);}catch(e){console.warn('TRG SPC overlay failed',key,e)}}
  function toggleSite(on){if(on){if(!sitePanel)createSitePanel();sitePanel.style.display='block';updateSite();}else if(sitePanel)sitePanel.style.display='none';}
  function createSitePanel(){const map=document.querySelector('.radar-map');if(!map)return;sitePanel=document.createElement('div');sitePanel.id='trgSitePanel';sitePanel.innerHTML=`<div class="trg-site-head"><b>HIGH-RES SINGLE-SITE RADAR</b><span>NOAA / NWS</span></div><div class="trg-site-controls"><select id="trgRadarSite"></select><select id="trgRadarProduct"><option value="reflectivity">Super-Res Reflectivity</option><option value="velocity">Base Velocity</option></select><button id="trgOpenNws">OPEN FULL NWS RADAR →</button></div><div class="trg-site-image-wrap"><img id="trgSiteImage" alt="High-resolution NEXRAD radar site product"><div id="trgSiteStatus">Loading…</div></div>`;map.insertAdjacentElement('afterend',sitePanel);const sel=sitePanel.querySelector('#trgRadarSite');RADARS.forEach(r=>{const o=document.createElement('option');o.value=r[0];o.textContent=`${r[0]} — ${r[1]}`;sel.appendChild(o)});sel.value='KINX';sitePanel.querySelector('#trgRadarProduct').addEventListener('change',updateSite);sel.addEventListener('change',()=>{const r=RADARS.find(x=>x[0]===sel.value);if(r&&window.state?.map)state.map.setView([r[2],r[3]],7);updateSite()});sitePanel.querySelector('#trgOpenNws').addEventListener('click',()=>window.open(`https://radar.weather.gov/?rid=${sel.value.slice(1)}`,'_blank','noopener'));}
  function updateSite(){const site=document.querySelector('#trgRadarSite')?.value||'KINX',prod=document.querySelector('#trgRadarProduct')?.value||'reflectivity',img=document.querySelector('#trgSiteImage'),status=document.querySelector('#trgSiteStatus');if(!img)return;const path=prod==='velocity'?'base_velocity/':'';img.src=`https://radar.weather.gov/ridge/standard/${path}${site}_0.gif?trg=${Date.now()}`;if(status)status.textContent=`${site} • ${prod==='velocity'?'Base Velocity':'Super-Res Reflectivity'} • NWS standard image refresh`;}
  function style(){if(document.getElementById('trgRadarEnhanceStyle'))return;const s=document.createElement('style');s.id='trgRadarEnhanceStyle';s.textContent=`.trg-radar-controls{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-top:10px}.trg-layer-title{font-size:10px;font-weight:900;color:#8d94a7;letter-spacing:1px}.trg-layer-btn{background:#0d1017;color:#b8bdca;border:1px solid #ffffff18;border-radius:6px;padding:7px 9px;font-size:9px;font-weight:900;cursor:pointer}.trg-layer-btn.active{color:#fff;border-color:#ff3030;background:#180b0b}.trg-layer-btn:hover{border-color:#ff3030}.trg-site-panel{margin-top:14px}.trg-site-head{display:flex;justify-content:space-between;align-items:center;background:#090c12;border:1px solid #ffffff16;padding:10px 12px;color:#fff;font-size:11px}.trg-site-head span{color:#8d94a7}.trg-site-controls{display:flex;flex-wrap:wrap;gap:8px;padding:10px;background:#0b0e14;border:1px solid #ffffff12;border-top:0}.trg-site-controls select,.trg-site-controls button{background:#11151d;color:#fff;border:1px solid #ffffff20;border-radius:5px;padding:8px;font-size:10px}.trg-site-controls button{font-weight:900;cursor:pointer}.trg-site-image-wrap{background:#020408;border:1px solid #ffffff12;text-align:center;padding:8px}.trg-site-image-wrap img{display:block;width:min(100%,900px);max-height:560px;object-fit:contain;margin:auto}.trg-site-image-wrap div{font-size:9px;color:#8d94a7;padding:7px}.trg-site-panel{display:none}`;document.head.appendChild(s)}
  function clickRouting(){document.addEventListener('click',e=>{const target=e.target.closest?.('.ticker-item[data-alert-id],a.alert');if(!target)return;const id=target.dataset.alertId||(()=>{try{return new URL(target.href,location.href).searchParams.get('alert')}catch{return null}})();if(id){e.preventDefault();e.stopImmediatePropagation();location.href=`maps.html?alert=${encodeURIComponent(id)}`;}},true)}
  function init(){style();clickRouting();controls();if(!document.getElementById('radarMap'))return;const wait=()=>{if(window.state?.map){loadWarnings();const id=new URLSearchParams(location.search).get('alert');if(id)loadWarnings(decodeURIComponent(id));}else setTimeout(wait,250)};wait();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
