/* TRG Radar V76 — SPC overlays + Wind/Hail CIG, isolated from Severe page. */
(()=>{
const SPC='https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/SPC_wx_outlks/FeatureServer';
const layers={categorical:1,tornado:3,wind:7,hail:5,windCig:6,hailCig:4};
let M=null,overlay={},cig={};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function init(){M=window.__trgRadarMap;if(!M||document.getElementById('trgSpc76'))return;if(!document.querySelector('.radar-toolbar'))return;const d=document.createElement('div');d.id='trgSpc76';d.style.cssText='display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-top:10px';d.innerHTML='<span style="font:900 9px Arial;color:#8d94a7;letter-spacing:1px">SPC</span><button data-k="categorical">SPC RISK</button><button data-k="tornado">TORNADO</button><button data-k="wind">WIND</button><button data-k="hail">HAIL</button>';d.querySelectorAll('button').forEach(b=>{b.style.cssText='background:#0d1017;color:#b8bdca;border:1px solid #ffffff18;border-radius:6px;padding:7px 9px;font:900 9px Arial;cursor:pointer';b.onclick=()=>{const k=b.dataset.k,on=b.dataset.on!=='1';b.dataset.on=on?'1':'0';b.style.background=on?'#180b0b':'#0d1017';b.style.color=on?'#fff':'#b8bdca';spc(k,on)}});document.querySelector('.radar-toolbar').appendChild(d)}
async function spc(k,on){if(!M)return;if(!on){if(overlay[k]){M.removeLayer(overlay[k]);overlay[k]=null}if(cig[k]){M.removeLayer(cig[k]);cig[k]=null}return}try{if(overlay[k])M.removeLayer(overlay[k]);const d=await fetch(`${SPC}/${layers[k]}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg76=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());overlay[k]=L.geoJSON(d,{style:f=>{const p=f.properties||{},n=Number(p.dn);const cat={2:'#c1e9c1',3:'#66a366',4:'#ffe066',5:'#ffa366',6:'#e06666',8:'#ee99ee'},prob={2:'#c1e9c1',5:'#ffa366',10:'#ffe066',15:'#e06666',30:'#ee99ee',45:'#d85bd8',60:'#b22bce',75:'#8b008b',90:'#6b006b'};return{color:'#333',weight:1.3,fillColor:k==='categorical'?(cat[n]||'#d9d9d9'):(prob[n]||'#d9d9d9'),fillOpacity:.30}}}).addTo(M);if(k==='wind'||k==='hail')await loadCig(k)}catch(e){console.warn('SPC overlay V76 failed',e)}}
async function loadCig(k){if(cig[k])M.removeLayer(cig[k]);const layer=k==='wind'?layers.windCig:layers.hailCig;const d=await fetch(`${SPC}/${layer}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg76=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());const fs=(d.features||[]).filter(f=>{const p=f.properties||{},x=String(p.label||p.LABEL||p.cig||'').toUpperCase();return /^CIG[123]$/.test(x)||['1','2','3'].includes(String(p.dn??p.DN??''))});cig[k]=L.geoJSON({...d,features:fs},{style:f=>{const p=f.properties||{},x=String(p.label||p.LABEL||p.cig||'').toUpperCase()||({1:'CIG1',2:'CIG2',3:'CIG3'}[String(p.dn??p.DN??'')]||'CIG1'),fill=x==='CIG1'?'#fff':x==='CIG2'?'#ffd166':'#ff7b72';return{color:'#111',weight:2,fillColor:fill,fillOpacity:.20,dashArray:x==='CIG1'?'8 5':x==='CIG2'?'12 5':'4 4'}},onEachFeature:(f,l)=>{const p=f.properties||{},x=String(p.label||p.LABEL||p.cig||'').toUpperCase()||'CIG';l.bindTooltip(x,{sticky:true})}}).addTo(M)}
const t=setInterval(()=>{if(window.__trgRadarMap){clearInterval(t);init()}},100);setTimeout(()=>clearInterval(t),15000);
})();
