/* TRG Radar V79 — map-native high-res NEXRAD + warning overlay. */
(()=>{
const WWA='https://mapservices.weather.noaa.gov/eventdriven/rest/services/WWA/watch_warn_adv/FeatureServer/0/query';
const ALERTS='https://api.weather.gov/alerts/active?limit=500';
let M=null,warningLayer=null,siteLayer=null,localRadar=null,sites=[],ready=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function capture(m){if(m?.getContainer?.().id!=='radarMap')return;M=m;window.__trgRadarMap=m;setTimeout(init,0)}
if(window.L&&!window.__trgRadar79){window.__trgRadar79=1;L.Map.addInitHook(function(){capture(this)})}
const wait=setInterval(()=>{if(M){clearInterval(wait);return}if(window.L&&!window.__trgRadar79){window.__trgRadar79=1;L.Map.addInitHook(function(){capture(this)})}},50);setTimeout(()=>clearInterval(wait),15000);
function init(){if(ready||!M)return;ready=true;const css=document.createElement('style');css.textContent=`.trg79{background:#080b11ee;border:1px solid #ffffff25;border-radius:7px;overflow:hidden;min-width:170px;box-shadow:0 4px 18px #0008}.trg79 button{display:block;width:100%;background:#10151d;color:#fff;border:0;border-bottom:1px solid #ffffff18;padding:8px 10px;font:900 9px Arial;cursor:pointer;text-align:left}.trg79 button.on{background:#176b39}.trg79 .menu{display:none;width:300px;max-height:340px;overflow:auto;padding:5px;background:#080b11}.trg79 .menu.open{display:block}.trg79 input{width:100%;box-sizing:border-box;background:#151a23;color:#fff;border:1px solid #ffffff22;padding:6px;margin-bottom:5px}.trg79 .site{display:block;width:100%;padding:6px;border:0;border-bottom:1px solid #ffffff12;background:#11161f;color:#fff;text-align:left;font:800 9px Arial;cursor:pointer}.trg79 .site:hover,.trg79 .site.active{background:#176b39}.trg79 small{display:block;color:#9aa1b1;font:700 8px Arial;padding:4px}.trg79label{background:#10151f;border:2px solid #fff;border-radius:999px;color:#fff;padding:3px 6px;font:900 9px Arial;white-space:nowrap;box-shadow:0 2px 8px #000b}.trg79label.active{background:#176b39;border-color:#7cffad}.trg79note{position:absolute;left:8px;bottom:8px;z-index:700;background:#080b11e8;color:#fff;padding:6px 8px;border-radius:4px;font:800 8px Arial;pointer-events:none}`;document.head.appendChild(css);
const c=L.DomUtil.create('div','trg79');c.id='trgRadar79';c.innerHTML='<button id="trg79warn">⚠ WARNINGS</button><button id="trg79sites">📡 HIGH-RES SITES</button><div id="trg79menu" class="menu"><input id="trg79search" placeholder="Search all NEXRAD radar sites"><small>All WSR-88D sites are listed. Click a site marker or station; the live single-site scan stays inside this map.</small><div id="trg79list"></div></div>';
const Ctl=L.Control.extend({onAdd:()=>{L.DomEvent.disableClickPropagation(c);L.DomEvent.disableScrollPropagation(c);return c}});M.addControl(new Ctl({position:'topright'}));
document.getElementById('trg79warn').onclick=e=>{const on=e.currentTarget.classList.toggle('on');on?loadWarnings():removeWarnings()};
document.getElementById('trg79sites').onclick=e=>{const on=e.currentTarget.classList.toggle('on');document.getElementById('trg79menu').classList.toggle('open',on);if(on)loadSites().then(showSites);else removeSites()};
document.getElementById('trg79search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#trg79list .site').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};
loadSites();
}
async function loadWarnings(){removeWarnings();warningLayer=L.layerGroup().addTo(M);try{const u=new URL(WWA);u.searchParams.set('where',"(phenom='TO' OR phenom='SV' OR phenom='FF') AND sig='W'");u.searchParams.set('outFields','*');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');u.searchParams.set('_trg',Date.now());const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();(d.features||[]).forEach(f=>{const p=f.properties||{},ph=String(p.phenom||'').toUpperCase(),col=ph==='TO'?'#ef4444':ph==='SV'?'#f97316':'#22c55e';L.geoJSON(f,{style:{color:col,weight:3,fillColor:col,fillOpacity:.13},onEachFeature:(_,l)=>l.bindPopup(`<b>${esc(p.event||({'TO':'Tornado Warning','SV':'Severe Thunderstorm Warning','FF':'Flash Flood Warning'}[ph]||'Warning'))}</b><br>${esc(p.areaDesc||p.ugc||'')}<br><small>${esc(p.wfo||'NWS')}</small>`)}).addTo(warningLayer)});
const ar=await fetch(`${ALERTS}&_trg79=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/geo+json'}});if(ar.ok){const a=await ar.json();(a.features||[]).filter(f=>/^(Special Weather Statement|Severe Weather Statement)$/.test(f.properties?.event||'')&&f.geometry).forEach(f=>L.geoJSON(f,{style:{color:'#a78bfa',weight:2,fillColor:'#a78bfa',fillOpacity:.08}}).addTo(warningLayer))}
}catch(e){console.warn('Radar warning overlay V79 failed',e)}}
function removeWarnings(){if(warningLayer){M.removeLayer(warningLayer);warningLayer=null}}
async function loadSites(){if(sites.length)return sites;try{const r=await fetch('https://api.weather.gov/radar/stations?stationType=WSR-88D&limit=500',{cache:'no-store',headers:{Accept:'application/geo+json'}});if(!r.ok)throw Error(r.status);const d=await r.json();sites=(d.features||[]).map(f=>{const p=f.properties||{},co=f.geometry?.coordinates||[];const id=String(p.stationIdentifier||p.id||'').toUpperCase();return{id,name:p.name||id,lat:Number(co[1]),lon:Number(co[0])}}).filter(s=>/^K[A-Z0-9]{3}$/.test(s.id)&&Number.isFinite(s.lat)&&Number.isFinite(s.lon));return sites}catch(e){console.warn('NWS WSR-88D site list failed',e);return[]}}
function showSites(){if(!M||!sites.length)return;if(siteLayer)M.removeLayer(siteLayer);siteLayer=L.layerGroup().addTo(M);const list=document.getElementById('trg79list');if(list){list.innerHTML='';sites.forEach(s=>{const b=document.createElement('button');b.className='site';b.dataset.id=s.id;b.textContent=`${s.id} — ${s.name}`;b.onclick=()=>selectSite(s);list.appendChild(b)})}sites.forEach(s=>L.marker([s.lat,s.lon],{icon:siteIcon(s.id,false),keyboard:true,title:`${s.id} — ${s.name}`}).addTo(siteLayer).on('click',()=>selectSite(s)))}
function removeSites(){if(siteLayer){M.removeLayer(siteLayer);siteLayer=null}if(localRadar){M.removeLayer(localRadar);localRadar=null}document.querySelector('.trg79note')?.remove()}
function siteIcon(id,active){return L.divIcon({className:'',html:`<span class="trg79label${active?' active':''}">${esc(id)}</span>`,iconSize:[45,22],iconAnchor:[22,11]})}
function selectSite(s){document.querySelectorAll('#trg79list .site').forEach(b=>b.classList.toggle('active',b.dataset.id===s.id));siteLayer?.eachLayer(m=>{const ll=m.getLatLng(),near=Math.abs(ll.lat-s.lat)<.001&&Math.abs(ll.lng-s.lon)<.001;m.setIcon(siteIcon(s.id,near))});M.setView([s.lat,s.lon],8,{animate:false});activateLocalRadar(s)}
function activateLocalRadar(s){if(localRadar){M.removeLayer(localRadar);localRadar=null}const sector=s.id.substring(1);localRadar=L.tileLayer.wms('https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/ridge.cgi?',{layers:'single',sector,prod:'N0B',format:'image/png',transparent:true,opacity:1,version:'1.1.1',styles:'',crs:L.CRS.EPSG3857,attribution:'NEXRAD N0B • IEM'}).addTo(M);let n=document.querySelector('.trg79note');if(!n){n=document.createElement('div');n.className='trg79note';M.getContainer().appendChild(n)}n.textContent=`HIGH-RES RADAR • ${s.id} — ${s.name} • LIVE N0B`}
})();
