/* TRG Radar V80 — map-native NEXRAD site selection. */
(()=>{
const WWA='https://mapservices.weather.noaa.gov/eventdriven/rest/services/WWA/watch_warn_adv/FeatureServer/0/query';
let M=null,siteLayer=null,warningLayer=null,localRadar=null,sites=[],ready=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function start(){if(ready||!window.L||!window.__trgRadarMap)return;if(document.getElementById('trgRadar80'))return;M=window.__trgRadarMap;ready=true;const css=document.createElement('style');css.textContent='.trg80{background:#080b11ee;border:1px solid #ffffff25;border-radius:7px;overflow:hidden;min-width:180px;box-shadow:0 4px 18px #0008}.trg80 button{display:block;width:100%;background:#10151d;color:#fff;border:0;border-bottom:1px solid #ffffff18;padding:8px 10px;font:900 9px Arial;cursor:pointer;text-align:left}.trg80 button.on{background:#176b39}.trg80 .menu{display:none;width:310px;max-height:350px;overflow:auto;padding:5px;background:#080b11}.trg80 .menu.open{display:block}.trg80 input{width:100%;box-sizing:border-box;background:#151a23;color:#fff;border:1px solid #ffffff22;padding:6px;margin-bottom:5px}.trg80 .site{display:block;width:100%;padding:6px;border:0;border-bottom:1px solid #ffffff12;background:#11161f;color:#fff;text-align:left;font:800 9px Arial;cursor:pointer}.trg80 .site:hover,.trg80 .site.active{background:#176b39}.trg80 small{display:block;color:#9aa1b1;font:700 8px Arial;padding:4px}.trg80label{background:#10151f;border:2px solid #fff;border-radius:999px;color:#fff;padding:3px 6px;font:900 9px Arial;white-space:nowrap;box-shadow:0 2px 8px #000b}.trg80label.active{background:#176b39;border-color:#7cffad}.trg80note{position:absolute;left:8px;bottom:8px;z-index:700;background:#080b11e8;color:#fff;padding:6px 8px;border-radius:4px;font:800 8px Arial;pointer-events:none}';document.head.appendChild(css);
const c=L.DomUtil.create('div','trg80');c.id='trgRadar80';c.innerHTML='<button id="trg80warn">⚠ WARNINGS</button><button id="trg80sites">📡 HIGH-RES SITES</button><div id="trg80menu" class="menu"><input id="trg80search" placeholder="Search all WSR-88D sites"><small>Click a site on the map or list. The high-resolution scan remains inside this TRG map.</small><div id="trg80list"></div></div>';
const Ctl=L.Control.extend({onAdd:()=>{L.DomEvent.disableClickPropagation(c);L.DomEvent.disableScrollPropagation(c);return c}});M.addControl(new Ctl({position:'topright'}));
const w=document.getElementById('trg80warn'),s=document.getElementById('trg80sites'),menu=document.getElementById('trg80menu');w.onclick=()=>{const on=w.classList.toggle('on');on?loadWarnings():removeWarnings()};s.onclick=()=>{const on=s.classList.toggle('on');menu.classList.toggle('open',on);if(on)loadSites().then(showSites);else removeSites()};document.getElementById('trg80search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#trg80list .site').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};loadSites().then(showSites);
}
async function loadSites(){if(sites.length)return sites;try{const r=await fetch('https://api.weather.gov/radar/stations?stationType=WSR-88D&limit=500',{cache:'no-store',headers:{Accept:'application/geo+json,application/json'}});if(!r.ok)throw Error(r.status);const d=await r.json();sites=(d.features||[]).map(f=>{const p=f.properties||{},co=f.geometry?.coordinates||[];const id=String(p.stationIdentifier||p.id||'').toUpperCase();return{id,name:p.name||id,lat:Number(co[1]),lon:Number(co[0])}}).filter(s=>/^K[A-Z0-9]{3}$/.test(s.id)&&Number.isFinite(s.lat)&&Number.isFinite(s.lon));return sites}catch(e){console.warn('V80 radar station list failed',e);return[]}}
function icon(id,active){return L.divIcon({className:'',html:`<span class="trg80label${active?' active':''}">${esc(id)}</span>`,iconSize:[45,22],iconAnchor:[22,11]})}
function showSites(){if(!M||!sites.length)return;if(siteLayer)M.removeLayer(siteLayer);siteLayer=L.layerGroup().addTo(M);const list=document.getElementById('trg80list');list.innerHTML='';sites.forEach(st=>{const b=document.createElement('button');b.className='site';b.dataset.id=st.id;b.textContent=`${st.id} — ${st.name}`;b.onclick=()=>selectSite(st);list.appendChild(b);L.marker([st.lat,st.lon],{icon:icon(st.id,false),title:`${st.id} — ${st.name}`}).addTo(siteLayer).on('click',()=>selectSite(st))})}
function removeSites(){if(siteLayer){M.removeLayer(siteLayer);siteLayer=null}if(localRadar){M.removeLayer(localRadar);localRadar=null}document.querySelector('.trg80note')?.remove()}
function selectSite(st){document.querySelectorAll('#trg80list .site').forEach(b=>b.classList.toggle('active',b.dataset.id===st.id));siteLayer?.eachLayer(m=>{const ll=m.getLatLng();m.setIcon(icon(m.options.title?.slice(0,4)||'',Math.abs(ll.lat-st.lat)<.001&&Math.abs(ll.lng-st.lon)<.001))});M.setView([st.lat,st.lon],8,{animate:false});activateRadar(st)}
function activateRadar(st){if(localRadar){M.removeLayer(localRadar);localRadar=null}const sector=st.id.replace(/^K/,'');const url=`https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/ridge::${sector}-N0B-0/{z}/{x}/{y}.png`;localRadar=L.tileLayer(url,{opacity:.95,maxZoom:12,minZoom:3,attribution:'NEXRAD N0B • Iowa Environmental Mesonet'}).addTo(M);let n=document.querySelector('.trg80note');if(!n){n=document.createElement('div');n.className='trg80note';M.getContainer().appendChild(n)}n.textContent=`HIGH-RES NEXRAD • ${st.id} — ${st.name} • N0B`;setTimeout(()=>M.invalidateSize(),50)}
async function loadWarnings(){removeWarnings();warningLayer=L.layerGroup().addTo(M);try{const u=new URL(WWA);u.searchParams.set('where',"(phenom='TO' OR phenom='SV' OR phenom='FF') AND sig='W'");u.searchParams.set('outFields','*');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');u.searchParams.set('_trg',Date.now());const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();(d.features||[]).forEach(f=>{const p=f.properties||{},ph=String(p.phenom||'').toUpperCase(),col=ph==='TO'?'#ef4444':ph==='SV'?'#f97316':'#22c55e';L.geoJSON(f,{style:{color:col,weight:3,fillColor:col,fillOpacity:.13},onEachFeature:(_,l)=>l.bindPopup(`<b>${esc(p.event||'Warning')}</b><br>${esc(p.areaDesc||p.ugc||'')}<br><small>${esc(p.wfo||'NWS')}</small>`)}).addTo(warningLayer)})}catch(e){console.warn('V80 radar warning overlay failed',e)}}
function removeWarnings(){if(warningLayer){M.removeLayer(warningLayer);warningLayer=null}}
const timer=setInterval(()=>{if(window.__trgRadarMap){clearInterval(timer);start()}},100);setTimeout(()=>clearInterval(timer),30000);if(window.__trgRadarMap)start();
})();
