/* TRG Radar V76 — one map-native high-res radar owner. */
(()=>{
const EVENTS=new Set(['Tornado Warning','Tornado Emergency','Severe Thunderstorm Warning','Extreme Wind Warning','Flash Flood Warning','Flash Flood Emergency','Special Weather Statement','Severe Weather Statement']);
const COLORS={tornado:'#ef4444',severe:'#f97316',flash:'#22c55e',statement:'#a78bfa'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let M=null,warningLayer=null,siteLayer=null,localRadar=null,sites=[],inited=false;
function capture(m){if(m?.getContainer?.().id!=='radarMap')return;M=m;window.__trgRadarMap=m;setTimeout(init,0)}
function hook(){if(window.L&&!window.__trgRadar76){window.__trgRadar76=1;L.Map.addInitHook(function(){capture(this)})}}
hook();const timer=setInterval(()=>{if(M)clearInterval(timer);else hook()},50);setTimeout(()=>clearInterval(timer),15000);
function init(){if(inited||document.getElementById('trgRadar76'))return;inited=true;const css=document.createElement('style');css.id='trgRadar76css';css.textContent=`.trg76{background:#080b11ee;border:1px solid #ffffff25;border-radius:7px;overflow:hidden;min-width:155px;box-shadow:0 4px 18px #0008}.trg76 button{display:block;width:100%;background:#10151d;color:#fff;border:0;border-bottom:1px solid #ffffff18;padding:8px 10px;font:900 9px Arial;cursor:pointer;text-align:left}.trg76 button.on{background:#176b39}.trg76 .menu{display:none;width:285px;max-height:310px;overflow:auto;padding:5px;background:#080b11}.trg76 .menu.open{display:block}.trg76 input{width:100%;box-sizing:border-box;background:#151a23;color:#fff;border:1px solid #ffffff22;padding:6px;margin-bottom:5px}.trg76 .site{display:block;width:100%;padding:6px;border:0;border-bottom:1px solid #ffffff12;background:#11161f;color:#fff;text-align:left;font:800 9px Arial;cursor:pointer}.trg76 .site:hover,.trg76 .site.active{background:#176b39}.trg76 small{display:block;color:#9aa1b1;font:700 8px Arial;padding:4px}.trg76label{background:#10151f;border:2px solid #fff;border-radius:999px;color:#fff;padding:3px 6px;font:900 9px Arial;white-space:nowrap;box-shadow:0 2px 8px #000b}.trg76label.active{background:#176b39;border-color:#7cffad}.trg76note{position:absolute;left:8px;bottom:8px;z-index:700;background:#080b11e8;color:#fff;padding:6px 8px;border-radius:4px;font:800 8px Arial;pointer-events:none}`;document.head.appendChild(css);
const c=L.DomUtil.create('div','trg76');c.id='trgRadar76';c.innerHTML='<button id="trg76warn">⚠ WARNINGS</button><button id="trg76sites">📡 HIGH-RES SITES</button><div id="trg76menu" class="menu"><input id="trg76search" placeholder="Search all NWS radar sites"><small>Click a site marker or station below. The high-resolution scan stays inside this map.</small><div id="trg76list"></div></div>';
const Ctl=L.Control.extend({onAdd:()=>{L.DomEvent.disableClickPropagation(c);L.DomEvent.disableScrollPropagation(c);return c}});M.addControl(new Ctl({position:'topright'}));
document.getElementById('trg76warn').onclick=e=>{const on=e.currentTarget.classList.toggle('on');on?loadWarnings():removeWarnings()};
document.getElementById('trg76sites').onclick=e=>{const on=e.currentTarget.classList.toggle('on'),menu=document.getElementById('trg76menu');menu.classList.toggle('open',on);if(on)loadSites().then(showSites);else removeSites()};
document.getElementById('trg76search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#trg76list .site').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};loadSites();
}
async function loadWarnings(){try{const r=await fetch(`https://api.weather.gov/alerts/active?status=actual&message_type=alert&limit=5000&_trg76=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/geo+json'}});if(!r.ok)throw Error(r.status);const d=await r.json();removeWarnings();warningLayer=L.layerGroup().addTo(M);(d.features||[]).filter(f=>EVENTS.has(f.properties?.event)&&f.geometry&&(!f.properties?.expires||Date.parse(f.properties.expires)>Date.now())).forEach(f=>{const p=f.properties||{},e=p.event||'',k=e.toLowerCase().includes('tornado')?'tornado':e.toLowerCase().includes('severe')||e.toLowerCase().includes('extreme wind')?'severe':e.toLowerCase().includes('flash flood')?'flash':'statement',col=COLORS[k];L.geoJSON(f,{style:{color:col,weight:3,fillColor:col,fillOpacity:.16},onEachFeature:(_,l)=>l.bindPopup(`<b>${esc(e)}</b><br>${esc(p.headline||'')}<br><b>${esc(p.areaDesc||'')}</b><br><small>Expires ${p.expires?new Date(p.expires).toLocaleString():'unknown'}</small>`)}).addTo(warningLayer)});const id=new URLSearchParams(location.search).get('alert');if(id){const f=(d.features||[]).find(x=>String(x.id)===id||String(x.properties?.identifier)===id);if(f?.geometry){const g=L.geoJSON(f),b=g.getBounds();if(b.isValid())M.fitBounds(b.pad(.2),{animate:false,maxZoom:9})}}}catch(e){console.warn('Radar warning overlay failed',e)}}
function removeWarnings(){if(warningLayer){M.removeLayer(warningLayer);warningLayer=null}}
async function loadSites(){if(sites.length)return sites;try{const r=await fetch('https://api.weather.gov/radar/stations?limit=500',{cache:'no-store',headers:{Accept:'application/geo+json'}});if(!r.ok)throw Error(r.status);const d=await r.json();sites=(d.features||[]).map(f=>{const p=f.properties||{},co=f.geometry?.coordinates||[];return{id:p.stationIdentifier||p.id,name:p.name||p.stationIdentifier||p.id,lat:Number(co[1]),lon:Number(co[0])}}).filter(s=>s.id&&Number.isFinite(s.lat)&&Number.isFinite(s.lon));const list=document.getElementById('trg76list');if(list){list.innerHTML='';sites.forEach(s=>{const b=document.createElement('button');b.className='site';b.dataset.id=s.id;b.textContent=`${s.id} — ${s.name}`;b.onclick=()=>selectSite(s);list.appendChild(b)})}return sites}catch(e){console.warn('NWS radar site list failed',e);return[]}}
function showSites(){if(!M||!sites.length)return;if(siteLayer)M.removeLayer(siteLayer);siteLayer=L.layerGroup().addTo(M);sites.forEach(s=>L.marker([s.lat,s.lon],{icon:siteIcon(s.id,false),keyboard:true,title:`${s.id} — ${s.name}`}).addTo(siteLayer).on('click',()=>selectSite(s)))}
function removeSites(){if(siteLayer){M.removeLayer(siteLayer);siteLayer=null}if(localRadar){M.removeLayer(localRadar);localRadar=null}const n=M?.getContainer?.().querySelector('.trg76note');if(n)n.remove()}
function siteIcon(id,active){return L.divIcon({className:'',html:`<span class="trg76label${active?' active':''}">${esc(id)}</span>`,iconSize:null,iconAnchor:[20,11]})}
function selectSite(s){if(!M)return;document.querySelectorAll('#trg76list .site').forEach(b=>b.classList.toggle('active',b.dataset.id===s.id));siteLayer?.eachLayer(m=>{const p=m.getLatLng(),a=Math.abs(p.lat-s.lat)<.01&&Math.abs(p.lng-s.lon)<.01;m.setIcon(siteIcon(s.id,a))});M.setView([s.lat,s.lon],7,{animate:false});activateLocalRadar(s)}
function activateLocalRadar(s){if(localRadar){M.removeLayer(localRadar);localRadar=null}const sector=String(s.id).replace(/^K/,'');localRadar=L.tileLayer.wms('https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/ridge.cgi?',{layers:'single',sector,prod:'N0Q',format:'image/png',transparent:true,version:'1.1.1',opacity:.9,updateWhenIdle:true}).addTo(M);let n=M.getContainer().querySelector('.trg76note');if(!n){n=document.createElement('div');n.className='trg76note';M.getContainer().appendChild(n)}n.textContent=`HIGH-RES RADAR • ${s.id} — ${s.name} • LIVE SINGLE-SITE REFLECTIVITY`}
})();
