/* TRG Radar V82 — single map controller. Weather Alerts/scroller intentionally untouched. */
(()=>{
const SPC='https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/SPC_wx_outlks/FeatureServer';
const WWA='https://mapservices.weather.noaa.gov/eventdriven/rest/services/WWA/watch_warn_adv/FeatureServer/0/query';
const layers={categorical:1,tornado:3,wind:7,hail:5,windCig:6,hailCig:4};
let M=null,started=false,siteLayer=null,localRadar=null,warningLayer=null,sites=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const probColor=(n,k)=>{const v=Number(n);if(k==='tornado')return({2:'#48a868',5:'#7b5a3b',10:'#b07d3c',15:'#f3d34a',30:'#f28c28',45:'#e53935',60:'#d94ad8',75:'#8f2bbd',90:'#5b147f'}[v]||'#d8c39a');return({2:'#c1e9c1',5:'#7b5a3b',10:'#b07d3c',15:'#f3d34a',30:'#f28c28',45:'#e53935',60:'#d94ad8',75:'#8f2bbd',90:'#5b147f'}[v]||'#d8c39a')};
function capture(){if(!window.L||window.__trgRadarV82Capture)return;window.__trgRadarV82Capture=true;const old=window.L.map;window.L.map=function(id,...args){const m=old.call(this,id,...args);if(String(id)==='radarMap'){M=m;window.__trgRadarMap=m;setTimeout(build,0)}return m}}
function build(){if(started||!M)return;started=true;const css=document.createElement('style');css.textContent='.trg82{background:#080b11ee;border:1px solid #ffffff25;border-radius:7px;overflow:hidden;min-width:190px;box-shadow:0 4px 18px #0008}.trg82 button{display:block;width:100%;background:#10151d;color:#fff;border:0;border-bottom:1px solid #ffffff18;padding:8px 10px;font:900 9px Arial;cursor:pointer;text-align:left}.trg82 button.on{background:#176b39}.trg82 .menu{display:none;width:330px;max-height:380px;overflow:auto;padding:5px;background:#080b11}.trg82 .menu.open{display:block}.trg82 input{width:100%;box-sizing:border-box;background:#151a23;color:#fff;border:1px solid #ffffff22;padding:7px;margin-bottom:5px}.trg82 .site{display:block;width:100%;padding:6px;border:0;border-bottom:1px solid #ffffff12;background:#11161f;color:#fff;text-align:left;font:800 9px Arial;cursor:pointer}.trg82 .site:hover,.trg82 .site.active{background:#176b39}.trg82 small{display:block;color:#9aa1b1;font:700 8px Arial;padding:5px}.trg82label{background:#10151f;border:2px solid #fff;border-radius:999px;color:#fff;padding:3px 6px;font:900 9px Arial;white-space:nowrap;box-shadow:0 2px 8px #000b}.trg82label.active{background:#176b39;border-color:#7cffad}.trg82note{position:absolute;left:8px;bottom:8px;z-index:700;background:#080b11e8;color:#fff;padding:6px 8px;border-radius:4px;font:800 8px Arial;pointer-events:none}#trgSpc82{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-top:10px}#trgSpc82 button{background:#0d1017;color:#b8bdca;border:1px solid #ffffff18;border-radius:6px;padding:7px 9px;font:900 9px Arial;cursor:pointer}#trgSpc82 button.on{background:#180b0b;color:#fff}';document.head.appendChild(css);
const c=L.DomUtil.create('div','trg82');c.innerHTML='<button id="trg82warn">⚠ WARNINGS</button><button id="trg82sites">📡 SHOW ALL HIGH-RES RADARS</button><div id="trg82menu" class="menu"><input id="trg82search" placeholder="Search all WSR-88D sites"><small>All available WSR-88D sites are shown directly on this map. Click a marker to activate its scan.</small><div id="trg82list"></div></div>';
const C=L.Control.extend({onAdd:()=>{L.DomEvent.disableClickPropagation(c);L.DomEvent.disableScrollPropagation(c);return c}});M.addControl(new C({position:'topright'}));
const w=c.querySelector('#trg82warn'),s=c.querySelector('#trg82sites'),menu=c.querySelector('#trg82menu');w.onclick=()=>{const on=!w.classList.contains('on');w.classList.toggle('on',on);on?loadWarnings():removeWarnings()};s.onclick=async()=>{const on=!s.classList.contains('on');s.classList.toggle('on',on);menu.classList.toggle('open',on);if(on){s.textContent='📡 HIDE HIGH-RES RADARS';await loadSites();showSites()}else{s.textContent='📡 SHOW ALL HIGH-RES RADARS';removeSites()}};c.querySelector('#trg82search').oninput=e=>{const q=e.target.value.toLowerCase();c.querySelectorAll('#trg82list .site').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};
const spc=document.createElement('div');spc.id='trgSpc82';spc.innerHTML='<span style="font:900 9px Arial;color:#8d94a7;letter-spacing:1px">SPC</span><button data-k="categorical">SPC RISK</button><button data-k="tornado">TORNADO</button><button data-k="wind">WIND</button><button data-k="hail">HAIL</button>';document.querySelector('.radar-toolbar')?.appendChild(spc);spc.querySelectorAll('button').forEach(b=>b.onclick=()=>{const on=!b.classList.contains('on');b.classList.toggle('on',on);toggleSpc(b.dataset.k,on)});
}
async function loadSites(){if(sites.length)return sites;try{const r=await fetch('https://api.weather.gov/radar/stations?limit=500&_trg82='+Date.now(),{cache:'no-store',headers:{Accept:'application/geo+json, application/json','User-Agent':'TRGTornado weather map contact@trgtornado.com'}});if(!r.ok)throw Error(r.status);const d=await r.json();sites=(d.features||[]).map(f=>{const p=f.properties||{},co=f.geometry?.coordinates||[];return{id:String(p.stationIdentifier||p.id||'').toUpperCase(),name:p.name||p.stationIdentifier||'',lat:Number(co[1]),lon:Number(co[0]),type:String(p.stationType||'').toUpperCase()}}).filter(x=>/^K[A-Z0-9]{3}$/.test(x.id)&&Number.isFinite(x.lat)&&Number.isFinite(x.lon)&&(!x.type||x.type.includes('WSR')));return sites}catch(e){console.warn('V82 station list failed',e);return[]}}
function icon(id,active){return L.divIcon({className:'',html:`<span class="trg82label${active?' active':''}">${esc(id)}</span>`,iconSize:[45,22],iconAnchor:[22,11]})}
function showSites(){if(!M||!sites.length)return;if(siteLayer)M.removeLayer(siteLayer);siteLayer=L.layerGroup().addTo(M);const list=document.getElementById('trg82list');list.innerHTML='';sites.forEach(st=>{const b=document.createElement('button');b.className='site';b.dataset.id=st.id;b.textContent=`${st.id} — ${st.name}`;b.onclick=()=>selectSite(st);list.appendChild(b);L.marker([st.lat,st.lon],{icon:icon(st.id,false),title:`${st.id} — ${st.name}`}).addTo(siteLayer).on('click',()=>selectSite(st))})}
function removeSites(){if(siteLayer){M.removeLayer(siteLayer);siteLayer=null}if(localRadar){M.removeLayer(localRadar);localRadar=null}document.querySelector('.trg82note')?.remove()}
function selectSite(st){document.querySelectorAll('#trg82list .site').forEach(b=>b.classList.toggle('active',b.dataset.id===st.id));siteLayer?.eachLayer(m=>{const id=(m.options.title||'').slice(0,4);m.setIcon(icon(id,id===st.id))});M.setView([st.lat,st.lon],8,{animate:false});activateRadar(st)}
function activateRadar(st){if(localRadar){M.removeLayer(localRadar);localRadar=null}const sector=st.id.replace(/^K/,'');const url=`https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/ridge::${sector}-N0B-0/{z}/{x}/{y}.png`;localRadar=L.tileLayer(url,{opacity:.95,maxZoom:12,minZoom:3,attribution:'NEXRAD N0B • Iowa Environmental Mesonet'}).addTo(M);let n=document.querySelector('.trg82note');if(!n){n=document.createElement('div');n.className='trg82note';M.getContainer().appendChild(n)}n.textContent=`HIGH-RES NEXRAD • ${st.id} — ${st.name} • N0B`}
async function loadWarnings(){removeWarnings();warningLayer=L.layerGroup().addTo(M);try{const u=new URL(WWA);u.searchParams.set('where',"(phenom='TO' OR phenom='SV' OR phenom='FF') AND sig='W'");u.searchParams.set('outFields','*');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');u.searchParams.set('_trg',Date.now());const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();(d.features||[]).forEach(f=>{const p=f.properties||{},ph=String(p.phenom||'').toUpperCase(),col=ph==='TO'?'#ef4444':ph==='SV'?'#f97316':'#22c55e';L.geoJSON(f,{style:{color:col,weight:3,fillColor:col,fillOpacity:.13},onEachFeature:(_,l)=>l.bindPopup(`<b>${esc(p.event||'Warning')}</b><br>${esc(p.areaDesc||p.ugc||'')}<br><small>${esc(p.wfo||'NWS')}</small>`)}).addTo(warningLayer)})}catch(e){console.warn('V82 warning overlay failed',e)}}
function removeWarnings(){if(warningLayer){M.removeLayer(warningLayer);warningLayer=null}}
async function toggleSpc(k,on){if(!on){window.__trgSpc82Layers?.[k]?.forEach(x=>M.removeLayer(x));if(window.__trgSpc82Layers)window.__trgSpc82Layers[k]=[];return}try{const r=await fetch(`${SPC}/${layers[k]}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg82=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();const layer=L.geoJSON(d,{style:f=>{const p=f.properties||{},n=Number(p.dn??p.DN??p.prob??p.PROB);return{color:'#333',weight:1.3,fillColor:k==='categorical'?({2:'#c1e9c1',3:'#66a366',4:'#ffe066',5:'#ffa366',6:'#e06666',8:'#ee99ee'}[n]||'#d9d9d9'):probColor(n,k),fillOpacity:.30}}}).addTo(M);window.__trgSpc82Layers??={};window.__trgSpc82Layers[k]=[layer];if(k==='wind'||k==='hail')await loadCig(k)}catch(e){console.warn('V82 SPC failed',e)}}
async function loadCig(k){try{const layer=k==='wind'?layers.windCig:layers.hailCig;const r=await fetch(`${SPC}/${layer}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg82=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();const fs=(d.features||[]).filter(f=>{const p=f.properties||{},x=String(p.label||p.LABEL||p.cig||'').toUpperCase();return /^CIG[123]$/.test(x)||['1','2','3'].includes(String(p.dn??p.DN??''))});const layer=L.geoJSON({...d,features:fs},{style:f=>{const p=f.properties||{},x=String(p.label||p.LABEL||p.cig||'').toUpperCase()||({1:'CIG1',2:'CIG2',3:'CIG3'}[String(p.dn??p.DN??'')]||'CIG1');return{color:'#111',weight:2,fillColor:x==='CIG1'?'#fff':x==='CIG2'?'#ffd52e':'#f97316',fillOpacity:.20,dashArray:x==='CIG1'?'8 5':x==='CIG2'?'12 5':'4 4'}}}).addTo(M);window.__trgSpc82Layers??={};window.__trgSpc82Layers[k]??=[];window.__trgSpc82Layers[k].push(layer)}catch(e){console.warn('V82 CIG failed',e)}}
capture();const timer=setInterval(()=>{if(window.__trgRadarMap){M=window.__trgRadarMap;build();clearInterval(timer)}},100);setTimeout(()=>clearInterval(timer),30000);
})();
