/* TRG Radar V85 — map-native radar controls. */
(()=>{
if(!window.L)return;
const SPC='https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/SPC_wx_outlks/FeatureServer',WWA='https://mapservices.weather.noaa.gov/eventdriven/rest/services/WWA/watch_warn_adv/FeatureServer/0/query',NWS='https://api.weather.gov/alerts/active';
const layers={categorical:1,tornado:3,wind:7,hail:5,windCig:6,hailCig:4};let M=null,siteLayer=null,localRadar=null,warningLayer=null,sites=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=p=>{const v=[p?.dn,p?.DN,p?.prob,p?.PROB,p?.probability,p?.PCT,p?.label,p?.LABEL].find(x=>x!==undefined&&x!==null&&x!=='');const m=String(v??'').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):NaN};
const color=(n,k)=>k==='tornado'?({2:'#39a852',5:'#7b5a3b',10:'#a66b35',15:'#f3d34a',30:'#f28c28',45:'#e53935',60:'#d94ad8',75:'#8f2bbd',90:'#5b147f'}[n]||'#d8c39a'):({2:'#c1e9c1',5:'#7b5a3b',10:'#a66b35',15:'#f3d34a',30:'#f28c28',45:'#e53935',60:'#d94ad8',75:'#8f2bbd',90:'#5b147f'}[n]||'#d8c39a');
function init(map){if(M||!map?.getContainer||map.getContainer().id!=='radarMap')return;M=map;setTimeout(build,0)}L.Map.addInitHook?.(function(){init(this)});
function build(){if(!M||document.getElementById('trg85control'))return;const css=document.createElement('style');css.textContent='.trg85{background:#080b11ee;border:1px solid #ffffff28;border-radius:7px;min-width:205px;box-shadow:0 4px 18px #0008;overflow:hidden}.trg85 button{display:block;width:100%;box-sizing:border-box;background:#10151d;color:#fff;border:0;border-bottom:1px solid #ffffff18;padding:8px 10px;font:900 9px Arial;cursor:pointer;text-align:left}.trg85 button.on{background:#176b39}.trg85 .menu{display:none;width:310px;max-height:360px;overflow:auto;padding:5px;background:#080b11}.trg85 .menu.open{display:block}.trg85 input{width:100%;box-sizing:border-box;background:#151a23;color:#fff;border:1px solid #ffffff22;padding:7px;margin-bottom:5px}.trg85 .site{display:block;width:100%;padding:6px;border:0;border-bottom:1px solid #ffffff12;background:#11161f;color:#fff;text-align:left;font:800 9px Arial;cursor:pointer}.trg85 .site.active,.trg85 .site:hover{background:#176b39}.trg85 small{display:block;color:#9aa1b1;font:700 8px Arial;padding:5px}.trg85label{background:#10151f;border:2px solid #fff;border-radius:999px;color:#fff;padding:3px 6px;font:900 9px Arial;white-space:nowrap;box-shadow:0 2px 8px #000b}.trg85label.active{background:#176b39;border-color:#7cffad}.trg85note{position:absolute;left:8px;bottom:8px;z-index:1000;background:#080b11e8;color:#fff;padding:6px 8px;border-radius:4px;font:800 8px Arial;pointer-events:none}';document.head.appendChild(css);
const c=L.DomUtil.create('div','trg85');c.id='trg85control';c.innerHTML='<button id="trg85warn">⚠ WARNINGS</button><button id="trg85sites">📡 SHOW ALL HIGH-RES RADARS</button><div id="trg85menu" class="menu"><input id="trg85search" placeholder="Search all WSR-88D sites"><small>Click a radar marker to activate its N0B high-resolution scan inside this map.</small><div id="trg85list"></div></div>';const C=L.Control.extend({onAdd:()=>{L.DomEvent.disableClickPropagation(c);L.DomEvent.disableScrollPropagation(c);return c}});M.addControl(new C({position:'topright'}));
const w=c.querySelector('#trg85warn'),s=c.querySelector('#trg85sites'),menu=c.querySelector('#trg85menu');w.onclick=()=>{const on=!w.classList.contains('on');w.classList.toggle('on',on);on?loadWarnings():removeWarnings()};s.onclick=async()=>{const on=!s.classList.contains('on');s.classList.toggle('on',on);menu.classList.toggle('open',on);s.textContent=on?'📡 HIDE HIGH-RES RADARS':'📡 SHOW ALL HIGH-RES RADARS';if(on){await loadSites();showSites()}else removeSites()};c.querySelector('#trg85search').oninput=e=>{const q=e.target.value.toLowerCase();c.querySelectorAll('#trg85list .site').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};
const bar=document.querySelector('.radar-toolbar');if(bar&&!document.getElementById('trg85spc')){const sp=document.createElement('div');sp.id='trg85spc';sp.style.cssText='display:flex;gap:7px;flex-wrap:wrap;margin-top:8px';sp.innerHTML='<b style="font:900 9px Arial;color:#8d94a7;padding:7px 0">SPC</b><button data-k="categorical">SPC RISK</button><button data-k="tornado">TORNADO</button><button data-k="wind">WIND</button><button data-k="hail">HAIL</button>';bar.appendChild(sp);sp.querySelectorAll('button').forEach(b=>b.onclick=()=>{const on=!b.classList.contains('on');b.classList.toggle('on',on);toggleSpc(b.dataset.k,on)})}
const slider=document.getElementById('radarSlider'),label=document.getElementById('radarFrameTime');if(slider&&!slider.dataset.trg85){slider.dataset.trg85='1';slider.addEventListener('input',()=>{const v=Number(slider.value),max=Number(slider.max)||48;if(label)label.textContent=v>=max?'LIVE':`${Math.max(0,max-v)*5} MIN AGO`;document.dispatchEvent(new CustomEvent('trg:radar-frame',{detail:{index:v,max}}))});slider.dispatchEvent(new Event('input'))}}
async function loadSites(){if(sites.length)return sites;try{const r=await fetch('https://api.weather.gov/radar/stations?limit=500&_trg85='+Date.now(),{cache:'no-store',headers:{Accept:'application/geo+json,application/json'}});if(!r.ok)throw Error(r.status);const d=await r.json();sites=(d.features||[]).map(f=>{const p=f.properties||{},co=f.geometry?.coordinates||[];return{id:String(p.stationIdentifier||'').toUpperCase(),name:p.name||p.stationIdentifier||'',lat:Number(co[1]),lon:Number(co[0])}}).filter(x=>/^K[A-Z0-9]{3}$/.test(x.id)&&Number.isFinite(x.lat)&&Number.isFinite(x.lon));return sites}catch(e){console.warn('radar stations',e);return[]}}
function icon(id,a){return L.divIcon({className:'',html:`<span class="trg85label${a?' active':''}">${esc(id)}</span>`,iconSize:[45,22],iconAnchor:[22,11]})}
function showSites(){if(!M)return;if(siteLayer)M.removeLayer(siteLayer);siteLayer=L.layerGroup().addTo(M);const list=document.getElementById('trg85list');list.innerHTML='';sites.forEach(st=>{const b=document.createElement('button');b.className='site';b.dataset.id=st.id;b.textContent=`${st.id} — ${st.name}`;b.onclick=()=>selectSite(st);list.appendChild(b);L.marker([st.lat,st.lon],{icon:icon(st.id,false),title:st.id}).addTo(siteLayer).on('click',()=>selectSite(st))})}
function removeSites(){if(siteLayer){M.removeLayer(siteLayer);siteLayer=null}if(localRadar){M.removeLayer(localRadar);localRadar=null}document.querySelector('.trg85note')?.remove()}
function selectSite(st){document.querySelectorAll('#trg85list .site').forEach(b=>b.classList.toggle('active',b.dataset.id===st.id));siteLayer?.eachLayer(m=>m.setIcon(icon(m.options.title,m.options.title===st.id)));M.setView([st.lat,st.lon],8,{animate:false});if(localRadar)M.removeLayer(localRadar);const sector=st.id.replace(/^K/,'');localRadar=L.tileLayer(`https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/ridge::${sector}-N0B-0/{z}/{x}/{y}.png`,{opacity:.95,minZoom:3,maxZoom:16,zIndex:700,attribution:'NEXRAD N0B • Iowa Environmental Mesonet'}).addTo(M);localRadar.bringToFront();let n=document.querySelector('.trg85note');if(!n){n=document.createElement('div');n.className='trg85note';M.getContainer().appendChild(n)}n.textContent=`HIGH-RES NEXRAD • ${st.id} — ${st.name}`}
async function loadWarnings(){removeWarnings();warningLayer=L.layerGroup().addTo(M);try{const [a,g]=await Promise.all([fetch(`${NWS}?status=actual&_trg85=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/geo+json,application/json'}}).then(r=>r.json()),(()=>{const u=new URL(WWA);u.searchParams.set('where',"(phenom='TO' OR phenom='SV' OR phenom='FF') AND sig='W'");u.searchParams.set('outFields','*');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');return fetch(u,{cache:'no-store'}).then(r=>r.json())})()]);const seen=new Set();for(const f of [...(g.features||[]),...(a.features||[])]){const p=f.properties||{},e=String(p.event||'').toLowerCase();if(!/tornado warning|severe thunderstorm warning|flash flood warning/.test(e)||seen.has(f.id))continue;if(f.geometry){const col=e.includes('tornado')?'#ef4444':e.includes('severe')?'#f97316':'#22c55e';L.geoJSON(f,{style:{color:col,weight:3,fillColor:col,fillOpacity:.15}}).addTo(warningLayer);seen.add(f.id)}}}catch(e){console.warn('warning overlay',e)}}
function removeWarnings(){if(warningLayer){M.removeLayer(warningLayer);warningLayer=null}}
async function toggleSpc(k,on){window.__trg85spc??={};if(!on){(window.__trg85spc[k]||[]).forEach(x=>M.removeLayer(x));window.__trg85spc[k]=[];return}try{const r=await fetch(`${SPC}/${layers[k]}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg85=${Date.now()}`,{cache:'no-store'});const d=await r.json();const layer=L.geoJSON(d,{style:f=>{const p=f.properties||{},n=pct(p);return{color:'#333',weight:1.3,fillColor:k==='categorical'?'#6ba66b':color(n,k),fillOpacity:.30}}}).addTo(M);window.__trg85spc[k]=[layer];if(k==='wind'||k==='hail')await loadCig(k)}catch(e){console.warn('SPC',e)}}
async function loadCig(k){try{const r=await fetch(`${SPC}/${k==='wind'?layers.windCig:layers.hailCig}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson&_trg85=${Date.now()}`,{cache:'no-store'});const d=await r.json();const fs=(d.features||[]).filter(f=>/^CIG[123]$/i.test(String(f.properties?.label||f.properties?.LABEL||'')));const layer=L.geoJSON({...d,features:fs},{style:f=>{const x=String(f.properties?.label||f.properties?.LABEL||'').toUpperCase();return{color:'#111',weight:2,fillColor:x==='CIG1'?'#fff':x==='CIG2'?'#ffd52e':'#f97316',fillOpacity:.2,dashArray:x==='CIG1'?'8 5':x==='CIG2'?'12 5':'4 4'}}}).addTo(M);window.__trg85spc[k].push(layer)}catch(e){console.warn('CIG',e)}}
})();