/* TRG Radar V81 — map-native high-res sites + warnings. */
(()=>{
const WWA='https://mapservices.weather.noaa.gov/eventdriven/rest/services/WWA/watch_warn_adv/FeatureServer/0/query';
let M=null,siteLayer=null,warningLayer=null,localRadar=null,sites=[],started=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function capture(){if(!window.L||!window.L.map||window.__trgRadarV81Wrapped)return;window.__trgRadarV81Wrapped=true;const old=window.L.map;window.L.map=function(id,...args){const m=old.call(this,id,...args);if(String(id)==='radarMap'){window.__trgRadarMap=m;M=m;setTimeout(build,0)}return m};}
function build(){if(started||!M||!M.getContainer)return;started=true;const css=document.createElement('style');css.textContent='.trg81{background:#080b11ee;border:1px solid #ffffff25;border-radius:7px;overflow:hidden;min-width:185px;box-shadow:0 4px 18px #0008}.trg81 button{display:block;width:100%;background:#10151d;color:#fff;border:0;border-bottom:1px solid #ffffff18;padding:8px 10px;font:900 9px Arial;cursor:pointer;text-align:left}.trg81 button.on{background:#176b39}.trg81 .menu{display:none;width:320px;max-height:360px;overflow:auto;padding:5px;background:#080b11}.trg81 .menu.open{display:block}.trg81 input{width:100%;box-sizing:border-box;background:#151a23;color:#fff;border:1px solid #ffffff22;padding:6px;margin-bottom:5px}.trg81 .site{display:block;width:100%;padding:6px;border:0;border-bottom:1px solid #ffffff12;background:#11161f;color:#fff;text-align:left;font:800 9px Arial;cursor:pointer}.trg81 .site:hover,.trg81 .site.active{background:#176b39}.trg81 small{display:block;color:#9aa1b1;font:700 8px Arial;padding:4px}.trg81label{background:#10151f;border:2px solid #fff;border-radius:999px;color:#fff;padding:3px 6px;font:900 9px Arial;white-space:nowrap;box-shadow:0 2px 8px #000b}.trg81label.active{background:#176b39;border-color:#7cffad}.trg81note{position:absolute;left:8px;bottom:8px;z-index:700;background:#080b11e8;color:#fff;padding:6px 8px;border-radius:4px;font:800 8px Arial;pointer-events:none}';document.head.appendChild(css);
const c=L.DomUtil.create('div','trg81');c.innerHTML='<button id="trg81warn">⚠ WARNINGS</button><button id="trg81sites">📡 SHOW ALL HIGH-RES RADARS</button><div id="trg81menu" class="menu"><input id="trg81search" placeholder="Search all WSR-88D sites"><small>All available WSR-88D sites are shown directly on this map. Click a marker to activate its scan.</small><div id="trg81list"></div></div>';
const Ctl=L.Control.extend({onAdd:()=>{L.DomEvent.disableClickPropagation(c);L.DomEvent.disableScrollPropagation(c);return c}});M.addControl(new Ctl({position:'topright'}));
const w=document.getElementById('trg81warn'),s=document.getElementById('trg81sites'),menu=document.getElementById('trg81menu');w.onclick=()=>{const on=w.classList.toggle('on');on?loadWarnings():removeWarnings()};s.onclick=async()=>{const on=s.classList.toggle('on');menu.classList.toggle('open',on);if(on){s.textContent='📡 HIDE HIGH-RES RADARS';await loadSites();showSites()}else{s.textContent='📡 SHOW ALL HIGH-RES RADARS';removeSites()}};document.getElementById('trg81search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#trg81list .site').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};
}
async function loadSites(){if(sites.length)return sites;try{const r=await fetch('https://api.weather.gov/radar/stations?limit=500&_trg81='+Date.now(),{cache:'no-store',headers:{Accept:'application/geo+json, application/json'}});if(!r.ok)throw Error(r.status);const d=await r.json();sites=(d.features||[]).map(f=>{const p=f.properties||{},co=f.geometry?.coordinates||[];return{id:String(p.stationIdentifier||p.id||'').toUpperCase(),name:p.name||p.stationIdentifier||'',lat:Number(co[1]),lon:Number(co[0]),type:String(p.stationType||'').toUpperCase()}}).filter(s=>/^K[A-Z0-9]{3}$/.test(s.id)&&Number.isFinite(s.lat)&&Number.isFinite(s.lon)&&(!s.type||s.type.includes('WSR')));return sites}catch(e){console.warn('V81 radar station list failed',e);return[]}}
function icon(id,active){return L.divIcon({className:'',html:`<span class="trg81label${active?' active':''}">${esc(id)}</span>`,iconSize:[45,22],iconAnchor:[22,11]})}
function showSites(){if(!M||!sites.length)return;if(siteLayer)M.removeLayer(siteLayer);siteLayer=L.layerGroup().addTo(M);const list=document.getElementById('trg81list');list.innerHTML='';sites.forEach(st=>{const b=document.createElement('button');b.className='site';b.dataset.id=st.id;b.textContent=`${st.id} — ${st.name}`;b.onclick=()=>selectSite(st);list.appendChild(b);L.marker([st.lat,st.lon],{icon:icon(st.id,false),title:`${st.id} — ${st.name}`}).addTo(siteLayer).on('click',()=>selectSite(st))})}
function removeSites(){if(siteLayer){M.removeLayer(siteLayer);siteLayer=null}if(localRadar){M.removeLayer(localRadar);localRadar=null}document.querySelector('.trg81note')?.remove()}
function selectSite(st){document.querySelectorAll('#trg81list .site').forEach(b=>b.classList.toggle('active',b.dataset.id===st.id));siteLayer?.eachLayer(m=>{const id=(m.options.title||'').slice(0,4);m.setIcon(icon(id,id===st.id))});M.setView([st.lat,st.lon],8,{animate:false});activateRadar(st)}
function activateRadar(st){if(localRadar){M.removeLayer(localRadar);localRadar=null}const sector=st.id.replace(/^K/,'');const url=`https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/ridge::${sector}-N0B-0/{z}/{x}/{y}.png`;localRadar=L.tileLayer(url,{opacity:.95,maxZoom:12,minZoom:3,attribution:'NEXRAD N0B • Iowa Environmental Mesonet'}).addTo(M);let n=document.querySelector('.trg81note');if(!n){n=document.createElement('div');n.className='trg81note';M.getContainer().appendChild(n)}n.textContent=`HIGH-RES NEXRAD • ${st.id} — ${st.name} • N0B`}
async function loadWarnings(){removeWarnings();warningLayer=L.layerGroup().addTo(M);try{const u=new URL(WWA);u.searchParams.set('where',"(phenom='TO' OR phenom='SV' OR phenom='FF') AND sig='W'");u.searchParams.set('outFields','*');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');u.searchParams.set('_trg',Date.now());const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();(d.features||[]).forEach(f=>{const p=f.properties||{},ph=String(p.phenom||'').toUpperCase(),col=ph==='TO'?'#ef4444':ph==='SV'?'#f97316':'#22c55e';L.geoJSON(f,{style:{color:col,weight:3,fillColor:col,fillOpacity:.13},onEachFeature:(_,l)=>l.bindPopup(`<b>${esc(p.event||'Warning')}</b><br>${esc(p.areaDesc||p.ugc||'')}<br><small>${esc(p.wfo||'NWS')}</small>`)}).addTo(warningLayer)})}catch(e){console.warn('V81 radar warning overlay failed',e)}}
function removeWarnings(){if(warningLayer){M.removeLayer(warningLayer);warningLayer=null}}
capture();const timer=setInterval(()=>{if(window.__trgRadarMap){M=window.__trgRadarMap;build();clearInterval(timer)}},100);setTimeout(()=>clearInterval(timer),30000);})();
